#--------------------------------------------------------------------------
# save tracers, auxiliary variables and process rates to final output array
#--------------------------------------------------------------------------
# in the water column
for k in range(kmax):
    output_t_n2           [current_output_index][k]=output_vector_t_n2           [k]/output_count
    output_t_o2           [current_output_index][k]=output_vector_t_o2           [k]/output_count
    output_t_dic          [current_output_index][k]=output_vector_t_dic          [k]/output_count
    output_t_nh4          [current_output_index][k]=output_vector_t_nh4          [k]/output_count
    output_t_no3          [current_output_index][k]=output_vector_t_no3          [k]/output_count
    output_t_po4          [current_output_index][k]=output_vector_t_po4          [k]/output_count
    output_t_spp          [current_output_index][k]=output_vector_t_spp          [k]/output_count
    output_t_zoo          [current_output_index][k]=output_vector_t_zoo          [k]/output_count
    output_t_h2s          [current_output_index][k]=output_vector_t_h2s          [k]/output_count
    output_t_sul          [current_output_index][k]=output_vector_t_sul          [k]/output_count
    output_t_alk          [current_output_index][k]=output_vector_t_alk          [k]/output_count
    output_t_lip          [current_output_index][k]=output_vector_t_lip          [k]/output_count
    output_t_doc          [current_output_index][k]=output_vector_t_doc          [k]/output_count
    output_t_dop          [current_output_index][k]=output_vector_t_dop          [k]/output_count
    output_t_don          [current_output_index][k]=output_vector_t_don          [k]/output_count
    output_t_cdom         [current_output_index][k]=output_vector_t_cdom         [k]/output_count
    output_t_cya          [current_output_index][k]=output_vector_t_cya          [k]/output_count
    output_t_det          [current_output_index][k]=output_vector_t_det          [k]/output_count
    output_t_poc          [current_output_index][k]=output_vector_t_poc          [k]/output_count
    output_t_pocp         [current_output_index][k]=output_vector_t_pocp         [k]/output_count
    output_t_pocn         [current_output_index][k]=output_vector_t_pocn         [k]/output_count
    output_t_lpp          [current_output_index][k]=output_vector_t_lpp          [k]/output_count
    output_t_ipw          [current_output_index][k]=output_vector_t_ipw          [k]/output_count
    output_lr_assim_lpp   [current_output_index][k]=output_vector_lr_assim_lpp   [k]/output_count
    output_lr_assim_spp   [current_output_index][k]=output_vector_lr_assim_spp   [k]/output_count
    output_lr_assim_cya   [current_output_index][k]=output_vector_lr_assim_cya   [k]/output_count
    output_lr_assim_lpp_doc[current_output_index][k]=output_vector_lr_assim_lpp_doc[k]/output_count
    output_lr_assim_spp_doc[current_output_index][k]=output_vector_lr_assim_spp_doc[k]/output_count
    output_lr_assim_cya_doc[current_output_index][k]=output_vector_lr_assim_cya_doc[k]/output_count
    output_lr_assim_lpp_dop[current_output_index][k]=output_vector_lr_assim_lpp_dop[k]/output_count
    output_lr_assim_spp_dop[current_output_index][k]=output_vector_lr_assim_spp_dop[k]/output_count
    output_lr_assim_lpp_don[current_output_index][k]=output_vector_lr_assim_lpp_don[k]/output_count
    output_lr_assim_spp_don[current_output_index][k]=output_vector_lr_assim_spp_don[k]/output_count
    output_ref_p_sw       [current_output_index][k]=output_vector_ref_p_sw       [k]/output_count
    output_ref_n_sw       [current_output_index][k]=output_vector_ref_n_sw       [k]/output_count
    output_lr_pocp        [current_output_index][k]=output_vector_lr_pocp        [k]/output_count
    output_lr_dop         [current_output_index][k]=output_vector_lr_dop         [k]/output_count
    output_lr_pocn        [current_output_index][k]=output_vector_lr_pocn        [k]/output_count
    output_lr_don         [current_output_index][k]=output_vector_lr_don         [k]/output_count
    output_w_poc_var      [current_output_index][k]=output_vector_w_poc_var      [k]/output_count
    output_w_pocn_var     [current_output_index][k]=output_vector_w_pocn_var     [k]/output_count
    output_w_pocp_var     [current_output_index][k]=output_vector_w_pocp_var     [k]/output_count
    output_p_no3_assim_lpp[current_output_index][k]=output_vector_p_no3_assim_lpp[k]/output_count
    output_p_nh4_assim_lpp[current_output_index][k]=output_vector_p_nh4_assim_lpp[k]/output_count
    output_p_no3_assim_spp[current_output_index][k]=output_vector_p_no3_assim_spp[k]/output_count
    output_p_nh4_assim_spp[current_output_index][k]=output_vector_p_nh4_assim_spp[k]/output_count
    output_p_n2_assim_cya [current_output_index][k]=output_vector_p_n2_assim_cya [k]/output_count
    output_p_assim_lpp_doc[current_output_index][k]=output_vector_p_assim_lpp_doc[k]/output_count
    output_p_assim_spp_doc[current_output_index][k]=output_vector_p_assim_spp_doc[k]/output_count
    output_p_assim_cya_doc[current_output_index][k]=output_vector_p_assim_cya_doc[k]/output_count
    output_p_assim_lpp_dop[current_output_index][k]=output_vector_p_assim_lpp_dop[k]/output_count
    output_p_assim_spp_dop[current_output_index][k]=output_vector_p_assim_spp_dop[k]/output_count
    output_p_nh4_assim_lpp_don[current_output_index][k]=output_vector_p_nh4_assim_lpp_don[k]/output_count
    output_p_no3_assim_lpp_don[current_output_index][k]=output_vector_p_no3_assim_lpp_don[k]/output_count
    output_p_nh4_assim_spp_don[current_output_index][k]=output_vector_p_nh4_assim_spp_don[k]/output_count
    output_p_no3_assim_spp_don[current_output_index][k]=output_vector_p_no3_assim_spp_don[k]/output_count
    output_p_pocp_resp    [current_output_index][k]=output_vector_p_pocp_resp    [k]/output_count
    output_p_pocn_resp    [current_output_index][k]=output_vector_p_pocn_resp    [k]/output_count
    output_p_cya_mort_det_diff[current_output_index][k]=output_vector_p_cya_mort_det_diff[k]/output_count
    output_p_det_resp_nh4 [current_output_index][k]=output_vector_p_det_resp_nh4 [k]/output_count
    output_p_det_denit_nh4[current_output_index][k]=output_vector_p_det_denit_nh4[k]/output_count
    output_p_det_sulf_nh4 [current_output_index][k]=output_vector_p_det_sulf_nh4 [k]/output_count
    output_p_h2s_oxno3_sul[current_output_index][k]=output_vector_p_h2s_oxno3_sul[k]/output_count
    output_p_doc2pco      [current_output_index][k]=output_vector_p_doc2pco      [k]/output_count
    output_p_dop2pocp     [current_output_index][k]=output_vector_p_dop2pocp     [k]/output_count
    output_p_don2pocn     [current_output_index][k]=output_vector_p_don2pocn     [k]/output_count
    output_p_doc_resp     [current_output_index][k]=output_vector_p_doc_resp     [k]/output_count
    output_p_dop_resp     [current_output_index][k]=output_vector_p_dop_resp     [k]/output_count
    output_p_don_resp     [current_output_index][k]=output_vector_p_don_resp     [k]/output_count
# in the sediment
output_t_sed          [current_output_index]=output_scalar_t_sed          /output_count
output_t_ips          [current_output_index]=output_scalar_t_ips          /output_count
output_t_sed_poc      [current_output_index]=output_scalar_t_sed_poc      /output_count
output_t_sed_pocn     [current_output_index]=output_scalar_t_sed_pocn     /output_count
output_t_sed_pocp     [current_output_index]=output_scalar_t_sed_pocp     /output_count
output_p_sed_resp_nh4 [current_output_index]=output_scalar_p_sed_resp_nh4 /output_count
output_p_sed_biores_poc[current_output_index]=output_scalar_p_sed_biores_poc/output_count
output_p_sed_burial   [current_output_index]=output_scalar_p_sed_burial   /output_count
output_p_ips_burial   [current_output_index]=output_scalar_p_ips_burial   /output_count
output_p_poc_burial   [current_output_index]=output_scalar_p_poc_burial   /output_count
output_p_pocn_burial  [current_output_index]=output_scalar_p_pocn_burial  /output_count
output_p_pocp_burial  [current_output_index]=output_scalar_p_pocp_burial  /output_count
output_p_alk_btf      [current_output_index]=output_scalar_p_alk_btf      /output_count
# at the sea surface
output_k0_co2         [current_output_index]=output_scalar_k0_co2         /output_count
output_k1_co2         [current_output_index]=output_scalar_k1_co2         /output_count
output_k2_co2         [current_output_index]=output_scalar_k2_co2         /output_count
output_alk_boron      [current_output_index]=output_scalar_alk_boron      /output_count
output_alk_h2s        [current_output_index]=output_scalar_alk_h2s        /output_count
output_alk_water      [current_output_index]=output_scalar_alk_water      /output_count
output_alk_po4        [current_output_index]=output_scalar_alk_po4        /output_count
output_alk_co2        [current_output_index]=output_scalar_alk_co2        /output_count
output_alk_residual   [current_output_index]=output_scalar_alk_residual   /output_count
output_dalkc_dh3o     [current_output_index]=output_scalar_dalkc_dh3o     /output_count
output_dalkresidual_dpH[current_output_index]=output_scalar_dalkresidual_dpH/output_count
output_ph             [current_output_index]=output_scalar_ph             /output_count
output_h3o            [current_output_index]=output_scalar_h3o            /output_count
output_pco2           [current_output_index]=output_scalar_pco2           /output_count
output_schmidtnumber_co2[current_output_index]=output_scalar_schmidtnumber_co2/output_count
output_schmidtnumber_o2[current_output_index]=output_scalar_schmidtnumber_o2/output_count
output_schmidtnumber_n2[current_output_index]=output_scalar_schmidtnumber_n2/output_count

# now, set the temporary output vector to zero
output_vector_t_n2            = [0.0 for k in range(kmax)]
output_vector_t_o2            = [0.0 for k in range(kmax)]
output_vector_t_dic           = [0.0 for k in range(kmax)]
output_vector_t_nh4           = [0.0 for k in range(kmax)]
output_vector_t_no3           = [0.0 for k in range(kmax)]
output_vector_t_po4           = [0.0 for k in range(kmax)]
output_vector_t_spp           = [0.0 for k in range(kmax)]
output_vector_t_zoo           = [0.0 for k in range(kmax)]
output_vector_t_h2s           = [0.0 for k in range(kmax)]
output_vector_t_sul           = [0.0 for k in range(kmax)]
output_vector_t_alk           = [0.0 for k in range(kmax)]
output_vector_t_lip           = [0.0 for k in range(kmax)]
output_vector_t_doc           = [0.0 for k in range(kmax)]
output_vector_t_dop           = [0.0 for k in range(kmax)]
output_vector_t_don           = [0.0 for k in range(kmax)]
output_vector_t_cdom          = [0.0 for k in range(kmax)]
output_vector_t_cya           = [0.0 for k in range(kmax)]
output_vector_t_det           = [0.0 for k in range(kmax)]
output_vector_t_poc           = [0.0 for k in range(kmax)]
output_vector_t_pocp          = [0.0 for k in range(kmax)]
output_vector_t_pocn          = [0.0 for k in range(kmax)]
output_vector_t_lpp           = [0.0 for k in range(kmax)]
output_vector_t_ipw           = [0.0 for k in range(kmax)]
output_vector_lr_assim_lpp    = [0.0 for k in range(kmax)]
output_vector_lr_assim_spp    = [0.0 for k in range(kmax)]
output_vector_lr_assim_cya    = [0.0 for k in range(kmax)]
output_vector_lr_assim_lpp_doc = [0.0 for k in range(kmax)]
output_vector_lr_assim_spp_doc = [0.0 for k in range(kmax)]
output_vector_lr_assim_cya_doc = [0.0 for k in range(kmax)]
output_vector_lr_assim_lpp_dop = [0.0 for k in range(kmax)]
output_vector_lr_assim_spp_dop = [0.0 for k in range(kmax)]
output_vector_lr_assim_lpp_don = [0.0 for k in range(kmax)]
output_vector_lr_assim_spp_don = [0.0 for k in range(kmax)]
output_vector_ref_p_sw        = [0.0 for k in range(kmax)]
output_vector_ref_n_sw        = [0.0 for k in range(kmax)]
output_vector_lr_pocp         = [0.0 for k in range(kmax)]
output_vector_lr_dop          = [0.0 for k in range(kmax)]
output_vector_lr_pocn         = [0.0 for k in range(kmax)]
output_vector_lr_don          = [0.0 for k in range(kmax)]
output_vector_w_poc_var       = [0.0 for k in range(kmax)]
output_vector_w_pocn_var      = [0.0 for k in range(kmax)]
output_vector_w_pocp_var      = [0.0 for k in range(kmax)]
output_vector_p_no3_assim_lpp = [0.0 for k in range(kmax)]
output_vector_p_nh4_assim_lpp = [0.0 for k in range(kmax)]
output_vector_p_no3_assim_spp = [0.0 for k in range(kmax)]
output_vector_p_nh4_assim_spp = [0.0 for k in range(kmax)]
output_vector_p_n2_assim_cya  = [0.0 for k in range(kmax)]
output_vector_p_assim_lpp_doc = [0.0 for k in range(kmax)]
output_vector_p_assim_spp_doc = [0.0 for k in range(kmax)]
output_vector_p_assim_cya_doc = [0.0 for k in range(kmax)]
output_vector_p_assim_lpp_dop = [0.0 for k in range(kmax)]
output_vector_p_assim_spp_dop = [0.0 for k in range(kmax)]
output_vector_p_nh4_assim_lpp_don = [0.0 for k in range(kmax)]
output_vector_p_no3_assim_lpp_don = [0.0 for k in range(kmax)]
output_vector_p_nh4_assim_spp_don = [0.0 for k in range(kmax)]
output_vector_p_no3_assim_spp_don = [0.0 for k in range(kmax)]
output_vector_p_pocp_resp     = [0.0 for k in range(kmax)]
output_vector_p_pocn_resp     = [0.0 for k in range(kmax)]
output_vector_p_cya_mort_det_diff = [0.0 for k in range(kmax)]
output_vector_p_det_resp_nh4  = [0.0 for k in range(kmax)]
output_vector_p_det_denit_nh4 = [0.0 for k in range(kmax)]
output_vector_p_det_sulf_nh4  = [0.0 for k in range(kmax)]
output_vector_p_h2s_oxno3_sul = [0.0 for k in range(kmax)]
output_vector_p_doc2pco       = [0.0 for k in range(kmax)]
output_vector_p_dop2pocp      = [0.0 for k in range(kmax)]
output_vector_p_don2pocn      = [0.0 for k in range(kmax)]
output_vector_p_doc_resp      = [0.0 for k in range(kmax)]
output_vector_p_dop_resp      = [0.0 for k in range(kmax)]
output_vector_p_don_resp      = [0.0 for k in range(kmax)]
output_scalar_t_sed           = 0.0        
output_scalar_t_ips           = 0.0        
output_scalar_t_sed_poc       = 0.0        
output_scalar_t_sed_pocn      = 0.0        
output_scalar_t_sed_pocp      = 0.0        
output_scalar_p_sed_resp_nh4  = 0.0        
output_scalar_p_sed_biores_poc = 0.0        
output_scalar_p_sed_burial    = 0.0        
output_scalar_p_ips_burial    = 0.0        
output_scalar_p_poc_burial    = 0.0        
output_scalar_p_pocn_burial   = 0.0        
output_scalar_p_pocp_burial   = 0.0        
output_scalar_p_alk_btf       = 0.0        
output_scalar_k0_co2          = 0.0        
output_scalar_k1_co2          = 0.0        
output_scalar_k2_co2          = 0.0        
output_scalar_alk_boron       = 0.0        
output_scalar_alk_h2s         = 0.0        
output_scalar_alk_water       = 0.0        
output_scalar_alk_po4         = 0.0        
output_scalar_alk_co2         = 0.0        
output_scalar_alk_residual    = 0.0        
output_scalar_dalkc_dh3o      = 0.0        
output_scalar_dalkresidual_dpH = 0.0        
output_scalar_ph              = 0.0        
output_scalar_h3o             = 0.0        
output_scalar_pco2            = 0.0        
output_scalar_schmidtnumber_co2 = 0.0        
output_scalar_schmidtnumber_o2 = 0.0        
output_scalar_schmidtnumber_n2 = 0.0        
